### ISSUE TITLE
[1.12.2] Failed to read sound devices

### ISSUE THREAD

**Issue by RedXStone** [ichttt/MoreSoundConfig#10]
# Hello
I have a problem with reading sound devices. When I'm trying to change audio driver, I'm getting this error:

**Failed to read sound
Devices your audio driver might not support this feature.**

I'm using 2 sound devices notebook's sound devices (it's calls 2-High Definition Sound Device) and headphones and all drivers has installed and updated.
I'm using OC Windows 10.

Details in screenshots:
![2023-01-07_19 16 29](https://user-images.githubusercontent.com/46400591/211160502-61681f24-8ae5-4040-b7ec-4a5610ce6e68.png)
![image](https://user-images.githubusercontent.com/46400591/211166152-608352a8-292d-458e-8fe7-645ae648e264.png)

**Comment by ichttt** [comment]
Can you please send me the log file? It should print a more detailed error message to that file.

**Comment by RedXStone** [comment]
> Can you please send me the log file? It should print a more detailed error message to that file.

[latest.log](https://github.com/ichttt/SoundDeviceOptions/files/10369391/latest.log)

**Comment by ElEgAnZzA** [comment]
I have the exact same problem.

Maybe the error is caused by system language (me and the thread starter both have Russian set as the language)?


Log attached:

[latest.log](https://github.com/ichttt/SoundDeviceOptions/files/12124841/latest.log)

Here's the error message:

> [16:07:08] [Client thread/INFO] [moresoundconfig]: Reading sound devices
> [16:07:08] [Client thread/ERROR] [moresoundconfig]: Failed to reload device list! Unexpected error!
> java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 1
> 	at org.lwjgl.MemoryUtil.decodeImpl(MemoryUtil.java:336) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> 	at org.lwjgl.MemoryUtil.decode(MemoryUtil.java:305) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> 	at org.lwjgl.MemoryUtil.decodeUTF8(MemoryUtil.java:294) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> 	at org.lwjgl.openal.ALC10.alcGetString(ALC10.java:157) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> 	at ichttt.mods.moresoundconfig.SoundDevices.reloadDeviceList0(SoundDevices.java:55) ~[SoundDevices.class:?]
> 	at ichttt.mods.moresoundconfig.SoundDevices.reloadDeviceList(SoundDevices.java:39) [SoundDevices.class:?]
> 	at ichttt.mods.moresoundconfig.gui.GuiSound.actionPerformed(GuiSound.java:49) [GuiSound.class:?]
> 	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:443) [blk.class:?]
> 	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533) [blk.class:?]
> 	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501) [blk.class:?]
> 	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759) [bib.class:?]
> 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
> Caused by: java.nio.charset.MalformedInputException: Input length = 1
> 	at java.nio.charset.CoderResult.throwException(Unknown Source) ~[?:1.8.0_371]
> 	at org.lwjgl.MemoryUtil.decodeImpl(MemoryUtil.java:334) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> 	... 22 more

**Comment by RealFoxass** [comment]
I am also getting the same issue using the 1.12.2 pack this is the error that in the Minecraft log

[21:27:57] [Client thread/INFO] [moresoundconfig]: Reading sound devices
[21:27:57] [Client thread/ERROR] [moresoundconfig]: Failed to reload device list! Unexpected error!
java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 1
	at org.lwjgl.MemoryUtil.decodeImpl(MemoryUtil.java:336) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.MemoryUtil.decode(MemoryUtil.java:305) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.MemoryUtil.decodeUTF8(MemoryUtil.java:294) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.openal.ALC10.alcGetString(ALC10.java:157) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at ichttt.mods.moresoundconfig.SoundDevices.reloadDeviceList0(SoundDevices.java:55) ~[SoundDevices.class:?]
	at ichttt.mods.moresoundconfig.SoundDevices.reloadDeviceList(SoundDevices.java:39) [SoundDevices.class:?]
	at ichttt.mods.moresoundconfig.gui.GuiSound.actionPerformed(GuiSound.java:49) [GuiSound.class:?]
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:443) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501) [blk.class:?]
	at net.minecraft.client.Minecraft.runTick(MinecraftMixin.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(MinecraftMixin.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(MinecraftMixin.java:7614) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(Unknown Source) ~[?:1.8.0_371]
	at org.lwjgl.MemoryUtil.decodeImpl(MemoryUtil.java:334) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	... 27 more

**Comment by RealFoxass** [comment]
OK after testing more Id realized that when my Bluetooth headphone and only my Bluetooth headphone connect it stops working, It works with my JBL Bluetooth speaker but with my Airpods Max it doesn't work

edit: after trying to edit setting no matter what as long as my headphones are connected it won't work I think its has something to due with it have hand free drivers while my speaker just shows up as a speaker

**Comment by Hoshroin** [comment]
It looks like a charset problem. From the logs, it just seems like the lwjgl is doing something wrong. It tried to decode alcGetString()'s return value, but then the java.nio.charset.MalformedInputException just got thrown.
So it's not your audio devices' fault I guess.
Maybe I'll try to set my system language to EN and see if things work.

**Comment by Hoshroin** [comment]
> It looks like a charset problem. From the logs, it just seems like the lwjgl is doing something wrong. It tried to decode alcGetString()'s return value, but then the java.nio.charset.MalformedInputException just got thrown. So it's not your audio devices' fault I guess. Maybe I'll try to set my system language to EN and see if things work.

nope, the system language isn't the problem here. maybe alcGetString() some devices will just return weird value?

**Comment by hiwaku** [comment]
I had the same issue, and I renamed the audio device from "スピーカー" to "Speaker". It worked for me.
I think this issue is caused by audio device names that contain non-ASCII characters.

**Comment by douganater** [comment]
Didn't test renaming but after all the years with my PC trying in different ports & drivers multiple of the 1 headset were listed like

1- Headset
2- Headset
3- Headset
4- Headset

& 3 was active but the logs showed 4 was the problem.

Uninstalling all the unused ones (Keeping the drivers) was enough to get audio back after re-launching the game.
